CREATE TABLE IF NOT EXISTS School (
studentName VARCHAR(200) NOT NULL,
age INT,
className VARCHAR(10) NOT NULL, 
fatherName VARCHAR(20) NOT NULL, 
motherName VARCHAR(20) NOT NULL, 
address VARCHAR(30) NOT NULL
);